# Generated by Django 5.1.6 on 2026-07-09 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_barbersession_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbersession',
            name='confidence_score',
            field=models.IntegerField(default=0, help_text='Session confidence score (0-100)'),
        ),
        migrations.AddField(
            model_name='barbersession',
            name='session_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('ENDED', 'Ended')], default='PENDING', help_text='State machine status', max_length=20),
        ),
        migrations.AddField(
            model_name='barbersession',
            name='tracking_data',
            field=models.JSONField(default=dict, help_text='Per-frame tracking metrics and session data'),
        ),
        migrations.AlterField(
            model_name='barbersession',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
