# Generated by Django 5.1.6 on 2026-08-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_barbersession_confidence_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbersession',
            name='ended_by',
            field=models.CharField(choices=[('AI', 'AI Engine'), ('TIMEOUT', 'Timeout'), ('MANUAL', 'Manual')], default='AI', help_text='How the session was ended', max_length=20),
        ),
        migrations.AddField(
            model_name='barbersession',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last heartbeat from AI Engine', null=True),
        ),
        migrations.AddField(
            model_name='barbersession',
            name='timeout_reason',
            field=models.CharField(blank=True, help_text='Reason for session timeout (e.g., AI_CRASH, NETWORK_LOSS)', max_length=50, null=True),
        ),
    ]
